easy_admin:
  site_name: 'F1Tipp Admin'
  design:
    form_theme: # Both themes are needed for ckeditor integration
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    menu:
      - { entity: 'Result', icon: 'flag-checkered' }
      - { entity: 'Event', icon: 'calendar' }
      - { entity: 'Message', icon: 'envelope' }
      - { entity: 'Driver', icon: 'car' }
      - { entity: 'Information', icon: 'newspaper' }
  entities:
    Event:
      translation_domain: 'messages'
      label: 'admin_events'
      class: App\Entity\Event
      list:
        fields:
          - id
          - { property: 'weekendOrder', label: 'admin_event_weekend_order'}
          - { property: 'name', label: 'admin_event_name'}
          - { property: 'date_time', label: 'admin_event_date'}
          - { property: 'type', label: 'admin_event_type'}
        max_results: 50
      templates:
        field_text: 'admin/event_field_text.html.twig'
    Message:
      translation_domain: 'messages'
      label: 'admin_messages'
      class: App\Entity\Message
      list:
        fields: ['id', 'user.name', 'content', {property: 'dateTime', type: 'datetime' }]
        batch_actions: ['delete']
        actions: ['-edit', '-new']
    Driver:
      translation_domain: 'messages'
      label: 'admin_driver'
      class: App\Entity\Driver
      list:
        sort: 'point'
        max_results: 50
        filters: ['status']
      templates:
        list: 'admin/driver_list.html.twig'
    Information:
      translation_domain: 'messages'
      label: 'admin_information'
      class: App\Entity\Information
      form:
        fields: ['title', {property: 'content', type: 'fos_ckeditor'}, 'slug', 'news']
    Result:
      translation_domain: 'messages'
      label: 'admin_result'
      class: App\Entity\Result
      list:
        fields:
          - {property: 'event.name', label: 'admin_event_name'}
          - {property: 'event.date_time', type: 'datetime', label: 'admin_event_date'}
          - {property: 'event.type', label: 'admin_event_type'}
      templates:
        new: 'admin/result_new.html.twig'
        edit: 'admin/result_edit.html.twig'
        field_text: 'admin/event_field_text.html.twig'
  user:
    name_property_path: name