version: '2'

services:
    apache:
        build: .docker/apache
        container_name: f1tipp_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/f1tipp_sf4
        depends_on:
          - php

    db:
        image: mysql:5.6
        container_name: f1tipp_mysql
        restart: always
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: f1tipp
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        ports:
            - "3306:3306"

    php:
        build: .docker/php
        container_name: f1tipp_php
        volumes:
          - .:/home/wwwroot/f1tipp_sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: f1tipp_phpmyadmin
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
        depends_on:
            - db
        ports:
            - 8080:80
        links:
            - db

    maildev:
        image: djfarrelly/maildev
        container_name: f1tipp_maildev
        ports:
          - 8001:80
