version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/var/www/f1tipp_sf4
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./.docker/php74/PHP.Dockerfile
    volumes:
      - ./:/var/www/f1tipp_sf4
    links:
      - mysql_db
  mysql_db:
    image: mysql:5.6
    container_name: f1tipp_mysql
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: f1tipp
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: f1tipp_phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    depends_on:
      - mysql_db
    ports:
      - 8080:80
    links:
      - mysql_db
