App\Entity\Feed:
  attributes:
    pagination_items_per_page: 10
    formats:
      0: 'json'
    order:
      id: DESC

  collectionOperations: [ 'GET' ]

  itemOperations:
    get:
      method: 'GET'
